### ISSUE TITLE
Wording in README

### ISSUE THREAD

**Issue by PatrickRWright** [HenrikBengtsson/future.callr#26]
This sentence

**"The advantage with using a new R process for each future is that it is that the R environment is guaranteed not to be contaminated by previous futures..."**

should probably be

**"The advantage of using a new R process for each future is that the R environment is guaranteed not to be contaminated by previous futures..."**

I stumbled over this minor thing while reading and thought I'd share. I hope this is the right place.

**Comment by HenrikBengtsson** [comment]
Thanks a bunch; I've updated this (vignette + README) the way you suggested.
