### ISSUE TITLE
Is there any way to specify packages that should be included in any branch?

### ISSUE THREAD

**Issue by rowrowrowyourboat** [HenrikBengtsson/future.callr#9]
Is there any way to specify packages that should be included in any new instance that is started? In my case I use the magrittr pipe `%>%` frequently, but it doesn't appear to be working correctly as often it is not detected as a package being used. 

I know I can specify packages for each future that I call, but is there a way to just add it in once as an option in the beginning or something so I don't have to add it to every future?

**Comment by HenrikBengtsson** [comment]
Hi, yeah, no, you don't really want to do that. It against the goal of future ecosystem.  

First, just to clarify the philosophy behind futures, I noticed that you posted it here on the repository for 'future.callr' backend, but should expect the same behavior/problem with basically all future backends (except `sequential` and `multicore`).  So, you should see the same problem with `plan(multisession)`.  What I'm trying to say here is that your code should be the same regardless of future backend and if you ever find yourself trying to come up with a workaround for a specific backend, that's a good sign you either doing something wrong, or there's something in the future ecosystem that might not work as it should.

Second, the identification of globals and packages is done by the [globals](https://cran.r-project.org/web/packages/globals) package.  Over time it has gotten better and more corner cases are handled automatically.  There are a still things that we want to improve (https://github.com/HenrikBengtsson/globals/issues); some of the things are hard but some are doable and will be solved at some time.  So, in the long term, expect more globals and packages to be picked up automatically.

Having said all that, as you've noticed you can explicitly specify packages that you want to be attached.  An alternative is to give "hints" in the code, e.g.
```r
f <- future({
  stats::filter(x)
})
```
would make it explicit that the 'stats' packages need to be attached (in case it could not figure that out automatically from static-code inspection).

It's hard to give more clear advice without seeing some real examples.  So please share and let's see if there's something that can be done.
